// ═══════════════════════════════════════════════════════════
// Scoring metadata — zdroje, vzorečky, reference
// PID-5 & LPFS-SR metodologie a citace
// Přesné výpočetní vzorce s čísly položek
// ═══════════════════════════════════════════════════════════

export const SOURCES = {
  apa2013: {
    short: "APA (2013) — DSM-5 Section III",
    full: "American Psychiatric Association (2013). Diagnostic and Statistical Manual of Mental Disorders (5th ed.), Section III: Alternative DSM-5 Model for Personality Disorders (AMPD), pp. 773–781.",
    doi: null,
    url: "https://www.psychiatry.org/psychiatrists/practice/dsm",
  },
  apaPid5: {
    short: "APA — PID-5 plný formulář + skórovací klíč",
    full: "APA: The Personality Inventory for DSM-5 (PID-5) — Full Version, Adult. Oficiální formulář s pokyny ke skórování.",
    doi: null,
    url: "https://www.psychiatry.org/getmedia/594673a6-1b9b-4298-8b52-c4c652c4a4e2/APA-DSM5TR-ThePersonalityInventoryForDSM5FullVersionAdult.pdf",
    note: "Volně stažitelné PDF přímo od APA",
  },
  novopsych: {
    short: "NovoPsych — PID-5-SF přehled",
    full: "NovoPsych (2025). Personality Inventory for DSM-5 – Short Form (PID-5-SF): Scoring, interpretation, psychometrics.",
    doi: null,
    url: "https://novopsych.com/assessments/diagnosis/personality-inventory-for-dsm-5-short-form-pid-5-sf/",
    note: "Volně dostupný přehled skórování a interpretace",
  },
  lloydPreece: {
    short: "Lloyd & Preece — Psychometric Auto-Scorer",
    full: "Lloyd, E. & Preece, D. (2023). Lloyd & Preece Psychometric Auto-Scorer v1.4. The Psychology Centre of Western Australia.",
    doi: null,
    url: "https://psychologywa.com/psychometric/",
    note: "Volně stažitelný Excel s automatickým skórováním PID-5 a dalších testů",
  },
  morey2017: {
    short: "Morey (2017) — LPFS-SR",
    full: "Morey, L. C. (2017). Development and initial evaluation of a self-report form of the DSM-5 Level of Personality Functioning Scale. Psychological Assessment, 29(10), 1302–1308.",
    doi: "10.1037/pas0000450",
    url: "https://novopsych.com/assessments/diagnosis/personality-inventory-for-dsm-5-short-form-pid-5-sf/",
    note: "LPFS-SR referenční článek; přehled na NovoPsych",
  },
};

// ═══ PID-5 Facet Metadata — CORRECTED per APA official scoring key ═══
export const FACET_META = {
  "Anhedonie": {
    en: "Anhedonia", domain: "Odtažitost",
    items: [0, 22, 25, 29, 123, 154, 156, 188],
    get itemCount() { return this.items.length; },
    formulaExact: "Anhedonie = (Q1 + Q23 + Q26 + Q30R + Q124 + Q155R + Q157 + Q189) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Neschopnost prožívat nebo nemít zájem o zážitky; nedostatek potěšení z životních aktivit.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Úzkostnost": {
    en: "Anxiousness", domain: "Negativní afektivita",
    items: [78, 92, 94, 95, 108, 109, 129, 140, 173],
    get itemCount() { return this.items.length; },
    formulaExact: "Úzkostnost = (Q79 + Q93 + Q95 + Q96R + Q109 + Q110 + Q130 + Q141 + Q174) / 9",
    formulaMath: "= Σ odpovědí na 9 položek / 9",
    desc: "Intenzivní pocity nervozity, napětí nebo paniky; obavy z nejistoty; strach z rozpadu.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Vyhášení pozornosti": {
    en: "Attention Seeking", domain: "Antagonismus",
    items: [13, 42, 73, 110, 112, 172, 190, 210],
    get itemCount() { return this.items.length; },
    formulaExact: "Vyhášení pozornosti = (Q14 + Q43 + Q74 + Q111 + Q113 + Q173 + Q191 + Q211) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Jednání zaměřené na přitahování pozornosti; snaha být středem zájmu.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Bezcitnost": {
    en: "Callousness", domain: "Antagonismus",
    items: [10, 12, 18, 53, 71, 72, 89, 152, 165, 182, 197, 199, 206, 207],
    get itemCount() { return this.items.length; },
    formulaExact: "Bezcitnost = (Q11 + Q13 + Q19 + Q54 + Q72 + Q73 + Q90R + Q153 + Q166 + Q183 + Q198 + Q200 + Q207 + Q208) / 14",
    formulaMath: "= Σ odpovědí na 14 položek / 14",
    desc: "Nedostatek zájmu o pocity a problémy druhých; nedostatek viny či výčitek svědomí.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Klamavost": {
    en: "Deceitfulness", domain: "Antagonismus",
    items: [40, 52, 55, 75, 125, 133, 141, 205, 213, 217],
    get itemCount() { return this.items.length; },
    formulaExact: "Klamavost = (Q41 + Q53 + Q56 + Q76 + Q126 + Q134 + Q142R + Q206 + Q214 + Q218) / 10",
    formulaMath: "= Σ odpovědí na 10 položek / 10",
    desc: "Nečestnost a podvádění; zkreslování sebe sama; přikrašlování nebo vymýšlení událostí.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Depresivita": {
    en: "Depressivity", domain: "Odtažitost",
    items: [26, 60, 65, 80, 85, 103, 118, 147, 150, 162, 167, 168, 177, 211],
    get itemCount() { return this.items.length; },
    formulaExact: "Depresivita = (Q27 + Q61 + Q66 + Q81 + Q86 + Q104 + Q119 + Q148 + Q151 + Q163 + Q168 + Q169 + Q178 + Q212) / 14",
    formulaMath: "= Σ odpovědí na 14 položek / 14",
    desc: "Časté pocity smutku, beznaděje; sebekritičnost; sebevražedné myšlenky nebo chování.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Roztříštěnost": {
    en: "Distractibility", domain: "Disinhibice",
    items: [5, 28, 46, 67, 87, 117, 131, 143, 198],
    get itemCount() { return this.items.length; },
    formulaExact: "Roztříštěnost = (Q6 + Q29 + Q47 + Q68 + Q88 + Q118 + Q132 + Q144 + Q199) / 9",
    formulaMath: "= Σ odpovědí na 9 položek / 9",
    desc: "Obtíže se soustředěním; snadné rozptýlení vnějšími podněty.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Excentricita": {
    en: "Eccentricity", domain: "Psychoticismus",
    items: [4, 20, 23, 24, 32, 51, 54, 69, 70, 151, 171, 184, 204],
    get itemCount() { return this.items.length; },
    formulaExact: "Excentricita = (Q5 + Q21 + Q24 + Q25 + Q33 + Q52 + Q55 + Q70 + Q71 + Q152 + Q172 + Q185 + Q205) / 13",
    formulaMath: "= Σ odpovědí na 13 položek / 13",
    desc: "Divné, neobvyklé nebo bizarní chování, vzhled nebo řeč; zvláštní a nepředvídatelné myšlenky.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Emoční labilita": {
    en: "Emotional Lability", domain: "Negativní afektivita",
    items: [17, 61, 101, 121, 137, 164, 180],
    get itemCount() { return this.items.length; },
    formulaExact: "Emoční labilita = (Q18 + Q62 + Q102 + Q122 + Q138 + Q165 + Q181) / 7",
    formulaMath: "= Σ odpovědí na 7 položek / 7",
    desc: "Nestabilita emočních prožitků a nálad; emoce se snadno vyvolají, jsou intenzivní.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Grandiozita": {
    en: "Grandiosity", domain: "Antagonismus",
    items: [39, 64, 113, 178, 186, 196],
    get itemCount() { return this.items.length; },
    formulaExact: "Grandiozita = (Q40 + Q65 + Q114 + Q179 + Q187 + Q197) / 6",
    formulaMath: "= Σ odpovědí na 6 položek / 6",
    desc: "Přesvědčení, že je člověk nadřazen druhým a zaslouží si zvláštní zacházení.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Hostilita": {
    en: "Hostility", domain: "Negativní afektivita",
    items: [27, 31, 37, 84, 91, 115, 157, 169, 187, 215],
    get itemCount() { return this.items.length; },
    formulaExact: "Hostilita = (Q28 + Q32 + Q38 + Q85 + Q92 + Q116 + Q158 + Q170 + Q188 + Q216) / 10",
    formulaMath: "= Σ odpovědí na 10 položek / 10",
    desc: "Přetrvávající nebo časté pocity hněvu; podrážděnost v reakci na drobné urážky.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Impulzivita": {
    en: "Impulsivity", domain: "Disinhibice",
    items: [3, 15, 16, 21, 57, 203],
    get itemCount() { return this.items.length; },
    formulaExact: "Impulzivita = (Q4 + Q16 + Q17 + Q22 + Q58R + Q204) / 6",
    formulaMath: "= Σ odpovědí na 6 položek / 6",
    desc: "Jednání na základě momentálního impulzu; obtížná schopnost následovat plán.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Vyhýbání se intimitě": {
    en: "Intimacy Avoidance", domain: "Odtažitost",
    items: [88, 96, 107, 119, 144, 202],
    get itemCount() { return this.items.length; },
    formulaExact: "Vyhýbání se intimitě = (Q89 + Q97R + Q108 + Q120 + Q145 + Q203) / 6",
    formulaMath: "= Σ odpovědí na 6 položek / 6",
    desc: "Vyhýbání se blízkým nebo romantickým vztahům a intimnímu kontaktu.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Nezodpovědnost": {
    en: "Irresponsibility", domain: "Disinhibice",
    items: [30, 128, 155, 159, 170, 200, 209],
    get itemCount() { return this.items.length; },
    formulaExact: "Nezodpovědnost = (Q31 + Q129 + Q156 + Q160 + Q171 + Q201 + Q210R) / 7",
    formulaMath: "= Σ odpovědí na 7 položek / 7",
    desc: "Nedodržování finančních a jiných závazků; neplnění dohod a slibů.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Manipulativnost": {
    en: "Manipulativeness", domain: "Antagonismus",
    items: [106, 124, 161, 179, 218],
    get itemCount() { return this.items.length; },
    formulaExact: "Manipulativnost = (Q107 + Q125 + Q162 + Q180 + Q219) / 5",
    formulaMath: "= Σ odpovědí na 5 položek / 5",
    desc: "Používání lstivosti k ovlivňování nebo kontrole druhých; svádění, šarm, výřečnost.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Percepční dysregulace": {
    en: "Perceptual Dysregulation", domain: "Psychoticismus",
    items: [35, 36, 41, 43, 58, 76, 82, 153, 191, 192, 212, 216],
    get itemCount() { return this.items.length; },
    formulaExact: "Percepční dysregulace = (Q36 + Q37 + Q42 + Q44 + Q59 + Q77 + Q83 + Q154 + Q192 + Q193 + Q213 + Q217) / 12",
    formulaMath: "= Σ odpovědí na 12 položek / 12",
    desc: "Zvláštní smyslové zážitky; smíšení reality a fantazie; depersonalizace a derealizace.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Perseverace": {
    en: "Perseveration", domain: "Negativní afektivita",
    items: [45, 50, 59, 77, 79, 99, 120, 127, 136],
    get itemCount() { return this.items.length; },
    formulaExact: "Perseverace = (Q46 + Q51 + Q60 + Q78 + Q80 + Q100 + Q121 + Q128 + Q137) / 9",
    formulaMath: "= Σ odpovědí na 9 položek / 9",
    desc: "Setrvávání u nefunkčních přístupů; obtížná změna chování navzdory opakovaným neúspěchům.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Restriktivní afektivita": {
    en: "Restricted Affectivity", domain: "Odtažitost",
    items: [7, 44, 83, 90, 100, 166, 183],
    get itemCount() { return this.items.length; },
    formulaExact: "Restriktivní afektivita = (Q8 + Q45 + Q84 + Q91 + Q101 + Q167 + Q184) / 7",
    formulaMath: "= Σ odpovědí na 7 položek / 7",
    desc: "Malá reakce na emocionálně stimulující situace; omezené prožívání i projevování emocí.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Riskování": {
    en: "Risk Taking", domain: "Disinhibice",
    items: [2, 6, 34, 38, 47, 66, 68, 86, 97, 111, 158, 163, 194, 214],
    get itemCount() { return this.items.length; },
    formulaExact: "Riskování = (Q3 + Q7R + Q35R + Q39 + Q48 + Q67 + Q69 + Q87R + Q98R + Q112 + Q159 + Q164R + Q195 + Q215R) / 14",
    formulaMath: "= Σ odpovědí na 14 položek / 14",
    desc: "Účast na nebezpečných aktivitách bez ohledu na důsledky. ⚠ Na úrovni domény invertováno (pól kompulzivity).",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Separační nejistota": {
    en: "Separation Insecurity", domain: "Negativní afektivita",
    items: [11, 49, 56, 63, 126, 148, 174],
    get itemCount() { return this.items.length; },
    formulaExact: "Separační nejistota = (Q12 + Q50 + Q57 + Q64 + Q127 + Q149 + Q175) / 7",
    formulaMath: "= Σ odpovědí na 7 položek / 7",
    desc: "Strach z odmítnutí nebo oddělení od významných druhých; obavy ze ztráty.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Submisivita": {
    en: "Submissiveness", domain: "Negativní afektivita",
    items: [8, 14, 62, 201],
    get itemCount() { return this.items.length; },
    formulaExact: "Submisivita = (Q9 + Q15 + Q63 + Q202) / 4",
    formulaMath: "= Σ odpovědí na 4 položek / 4",
    desc: "Přizpůsobení se přáním a potřebám druhých; podřizování vlastního jednání.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Podezřívavost": {
    en: "Suspiciousness", domain: "Odtažitost",
    items: [1, 102, 116, 130, 132, 176, 189],
    get itemCount() { return this.items.length; },
    formulaExact: "Podezřívavost = (Q2 + Q103 + Q117 + Q131R + Q133 + Q177R + Q190) / 7",
    formulaMath: "= Σ odpovědí na 7 položek / 7",
    desc: "Očekávání zlomyslnosti od druhých; pochybování o loajalitě.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Neobvyklé přesvědčení": {
    en: "Unusual Beliefs & Experiences", domain: "Psychoticismus",
    items: [93, 98, 105, 138, 142, 149, 193, 208],
    get itemCount() { return this.items.length; },
    formulaExact: "Neobvyklé přesvědčení = (Q94 + Q99 + Q106 + Q139 + Q143 + Q150 + Q194 + Q209) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Přesvědčení o nadpřirozených schopnostech; neobvyklé zážitky s realitou.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Stažení": {
    en: "Withdrawal", domain: "Odtažitost",
    items: [9, 19, 74, 81, 135, 145, 146, 160, 181, 185],
    get itemCount() { return this.items.length; },
    formulaExact: "Stažení = (Q10 + Q20 + Q75 + Q82 + Q136 + Q146 + Q147 + Q161 + Q182 + Q186) / 10",
    formulaMath: "= Σ odpovědí na 10 položek / 10",
    desc: "Preference pro samotu; rezervovanost v sociálních situacích.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
  "Rigidita": {
    en: "Rigid Perfectionism", domain: "Disinhibice",
    items: [33, 48, 104, 114, 122, 134, 139, 175, 195, 219],
    get itemCount() { return this.items.length; },
    formulaExact: "Rigidita = (Q34 + Q49 + Q105 + Q115 + Q123 + Q135 + Q140 + Q176 + Q196 + Q220) / 10",
    formulaMath: "= Σ odpovědí na 10 položek / 10",
    desc: "Přísné trvání na dokonalosti; rigidní dodržování pravidel. ⚠ Na úrovni domény invertováno.",
    source: "apaPid5", scoringSource: "apaPid5",
  },
};

// ═══ Domain Metadata — CORRECTED per APA ═══
export const DOMAIN_META = {
  "Negativní afektivita": {
    en: "Negative Affectivity",
    coreFacets: ["Emoční labilita", "Úzkostnost", "Separační nejistota"],
    allFacets: ["Emoční labilita", "Úzkostnost", "Separační nejistota", "Hostilita", "Perseverace", "Submisivita", "Restriktivní afektivita"],
    formulaExact: "Neg. afektivita = (Emoční labilita + Úzkostnost + Separační nejistota) / 3",
    formulaOfficial: "APA oficiální = (Emoční labilita + Úzkostnost + Separační nejistota) / 3",
    desc: "Časté a intenzivní prožívání negativních emocí a projevů chování z nich vyplývajících.",
    source: "apaPid5", cutoffSource: "novopsych",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Odtažitost": {
    en: "Detachment",
    coreFacets: ["Stažení", "Anhedonie", "Vyhýbání se intimitě"],
    allFacets: ["Stažení", "Vyhýbání se intimitě", "Anhedonie", "Depresivita", "Restriktivní afektivita", "Podezřívavost"],
    formulaExact: "Odtažitost = (Stažení + Anhedonie + Vyhýbání se intimitě) / 3",
    formulaOfficial: "APA oficiální = (Stažení + Anhedonie + Vyhýbání se intimitě) / 3",
    desc: "Stažení z mezilidských interakcí; omezený prožitek a projev emocí.",
    source: "apaPid5", cutoffSource: "novopsych",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Antagonismus": {
    en: "Antagonism",
    coreFacets: ["Manipulativnost", "Klamavost", "Grandiozita"],
    allFacets: ["Manipulativnost", "Klamavost", "Grandiozita", "Vyhášení pozornosti", "Bezcitnost"],
    formulaExact: "Antagonismus = (Manipulativnost + Klamavost + Grandiozita) / 3",
    formulaOfficial: "APA oficiální = (Manipulativnost + Klamavost + Grandiozita) / 3",
    desc: "Chování stavějící osobu do konfliktu s druhými; přehnané pocity vlastní důležitosti.",
    source: "apaPid5", cutoffSource: "novopsych",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Disinhibice": {
    en: "Disinhibition",
    coreFacets: ["Nezodpovědnost", "Impulzivita", "Roztříštěnost"],
    allFacets: ["Nezodpovědnost", "Impulzivita", "Roztříštěnost", "Riskování", "Rigidita"],
    formulaExact: "Disinhibice = (Nezodpovědnost + Impulzivita + Roztříštěnost) / 3",
    formulaOfficial: "APA oficiální = (Nezodpovědnost + Impulzivita + Roztříštěnost) / 3",
    desc: "Orientace na okamžité uspokojení; impulzivní chování bez ohledu na následky.",
    source: "apaPid5", cutoffSource: "novopsych",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Psychoticismus": {
    en: "Psychoticism",
    coreFacets: ["Neobvyklé přesvědčení", "Excentricita", "Percepční dysregulace"],
    allFacets: ["Neobvyklé přesvědčení", "Excentricita", "Percepční dysregulace"],
    formulaExact: "Psychoticismus = (Neobvyklé přesvědčení + Excentricita + Percepční dysregulace) / 3",
    formulaOfficial: "APA oficiální = (Neobvyklé přesvědčení + Excentricita + Percepční dysregulace) / 3",
    desc: "Široké spektrum kulturně inkongruentních, zvláštních chování a myšlení.",
    source: "apaPid5", cutoffSource: "novopsych",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
};

// ═══ General scoring info ═══
export const SCORING_INFO = {
  pid5: {
    scale: "0–3 (0 = Zcela nepravdivé, 1 = Částečně nepravdivé, 2 = Částečně pravdivé, 3 = Zcela pravdivé)",
    facetFormula: "Facetové skóre = průměr odpovědí na všechny položky dané facety (rozsah 0.00–3.00)",
    facetFormulaMath: "facet_score = Σ(item_responses) / n_items",
    domainFormula: "Doménové skóre = průměr facetových skórů přiřazených k doméně",
    domainFormulaMath: "domain_score = Σ(facet_scores) / n_facets_in_domain",
    diagFormula: "Diagnostické skóre = vážený průměr relevantních facetových skórů (váhy dle DSM-5 AMPD profilů)",
    diagFormulaMath: "diag_score = Σ(facet_score × weight) / Σ(weights)",
    cutoffs: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
    cutoffSource: "novopsych",
    source: "apaPid5",
    itemCount: 220, facetCount: 25, domainCount: 5,
  },
  lpfs: {
    scale: "1–4 (1 = Zcela nepravdivé, 2 = Trochu pravdivé, 3 = Převážně pravdivé, 4 = Zcela pravdivé)",
    totalFormula: "Celkové skóre = průměr všech 80 odpovědí",
    totalFormulaMath: "total_score = Σ(item_responses) / 80",
    subscales: "Identita (20 položek) · Sebesměrování (20) · Empatie (20) · Intimita (20)",
    subscaleFormula: "Subškálové skóre = průměr 20 položek dané subškály",
    higherOrder: "Sebe-fungování = průměr(Identita, Sebesměrování) · Interpersonální = průměr(Empatie, Intimita)",
    threshold: "Práh pro PD diagnózu: průměr ≥ 1.5 (= LPFS Level 2+, minimum pro diagnózu PD dle DSM-5 AMPD)",
    source: "morey2017",
    itemCount: 80,
  },
};
