// ═══════════════════════════════════════════════════════════
// Scoring metadata — zdroje, vzorečky, reference
// PID-5 & LPFS-SR metodologie a citace
// Přesné výpočetní vzorce s čísly položek
// ═══════════════════════════════════════════════════════════

export const SOURCES = {
  krueger2012: {
    short: "Krueger et al. (2012)",
    full: "Krueger, R. F., Derringer, J., Markon, K. E., Watson, D., & Skodol, A. E. (2012). Initial construction of a maladaptive personality trait model and inventory for DSM-5. Psychological Medicine, 42(9), 1879–1890.",
    doi: "10.1017/S0033291711002674",
    url: "https://doi.org/10.1017/S0033291711002674",
  },
  apa2013: {
    short: "APA (2013) — DSM-5 Section III",
    full: "American Psychiatric Association (2013). Diagnostic and Statistical Manual of Mental Disorders (5th ed.), Section III: Alternative DSM-5 Model for Personality Disorders (AMPD), pp. 773–781.",
    doi: null,
    url: "https://www.psychiatry.org/psychiatrists/practice/dsm",
  },
  bach2018: {
    short: "Bach, Sellbom & Simonsen (2018)",
    full: "Bach, B., Sellbom, M., & Simonsen, E. (2018). Personality Inventory for DSM-5 (PID-5) in clinical vs nonclinical individuals: Generalizability of psychometric features. Assessment, 25(7), 815–825.",
    doi: "10.1177/1073191116684281",
    url: "https://doi.org/10.1177/1073191116684281",
  },
  morey2017: {
    short: "Morey (2017)",
    full: "Morey, L. C. (2017). Development and initial evaluation of a self-report form of the DSM-5 Level of Personality Functioning Scale. Psychological Assessment, 29(10), 1302–1308.",
    doi: "10.1037/pas0000450",
    url: "https://doi.org/10.1037/pas0000450",
  },
  widiger2019: {
    short: "Widiger et al. (2019)",
    full: "Widiger, T. A., Bach, B., Chmielewski, M., et al. (2019). Criterion A of the AMPD in HiTOP. Journal of Personality Assessment, 101(4), 345–355.",
    doi: "10.1080/00223891.2018.1521946",
    url: "https://doi.org/10.1080/00223891.2018.1521946",
  },
  bach2016: {
    short: "Bach et al. (2016)",
    full: "Bach, B., Maples-Keller, J. L., Bo, S., & Simonsen, E. (2016). The alternative DSM-5 personality disorder traits criterion: A comparative examination. Personality Disorders, 7(2), 124–135.",
    doi: "10.1037/per0000162",
    url: "https://doi.org/10.1037/per0000162",
  },
  apaPid5: {
    short: "APA — PID-5 scoring manual",
    full: "APA Online Assessment Measures: The Personality Inventory for DSM-5 (PID-5) — Adult, scoring instructions.",
    doi: null,
    url: "https://www.psychiatry.org/psychiatrists/practice/dsm/educational-resources/assessment-measures",
  },
};

// ═══ PID-5 Facet Metadata ═══
export const FACET_META = {
  "Anhedonie": {
    en: "Anhedonia", domain: "Odtažitost",
    items: [0, 22, 25, 26, 123, 156, 188, 189],
    get itemCount() { return this.items.length; },
    formulaExact: "Anhedonie = (Q1 + Q23 + Q26 + Q27 + Q124 + Q157 + Q189 + Q190) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Neschopnost prožívat nebo nemít zájem o zážitky; nedostatek potěšení z životních aktivit.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Úzkostnost": {
    en: "Anxiousness", domain: "Negativní afektivita",
    items: [78, 92, 94, 108, 109, 129, 140, 173],
    get itemCount() { return this.items.length; },
    formulaExact: "Úzkostnost = (Q79 + Q93 + Q95 + Q109 + Q110 + Q130 + Q141 + Q174) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Intenzivní pocity nervozity, napětí nebo paniky; obavy z nejistoty; strach z rozpadu.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Vyhášení pozornosti": {
    en: "Attention Seeking", domain: "Antagonismus",
    items: [13, 42, 73, 110, 112, 172, 190, 210],
    get itemCount() { return this.items.length; },
    formulaExact: "Vyhášení pozornosti = (Q14 + Q43 + Q74 + Q111 + Q113 + Q173 + Q191 + Q211) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Jednání zaměřené na přitahování pozornosti; snaha být středem zájmu.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Bezcitnost": {
    en: "Callousness", domain: "Antagonismus",
    items: [18, 53, 71, 89, 152, 165, 182, 183],
    get itemCount() { return this.items.length; },
    formulaExact: "Bezcitnost = (Q19 + Q54 + Q72 + Q90 + Q153 + Q166 + Q183 + Q184) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Nedostatek zájmu o pocity a problémy druhých; nedostatek viny či výčitek svědomí.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Klamavost": {
    en: "Deceitfulness", domain: "Antagonismus",
    items: [40, 52, 55, 125, 133, 155, 161, 213],
    get itemCount() { return this.items.length; },
    formulaExact: "Klamavost = (Q41 + Q53 + Q56 + Q126 + Q134 + Q156 + Q162 + Q214) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Nečestnost a podvádění; zkreslování sebe sama; přikrašlování nebo vymýšlení událostí.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Depresivita": {
    en: "Depressivity", domain: "Odtažitost",
    items: [60, 65, 80, 103, 147, 150, 157, 168],
    get itemCount() { return this.items.length; },
    formulaExact: "Depresivita = (Q61 + Q66 + Q81 + Q104 + Q148 + Q151 + Q158 + Q169) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Časté pocity smutku, beznaděje; sebekritičnost; sebevražedné myšlenky nebo chování.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Roztříštěnost": {
    en: "Distractibility", domain: "Disinhibice",
    items: [5, 28, 67, 117, 131, 143, 198, 199],
    get itemCount() { return this.items.length; },
    formulaExact: "Roztříštěnost = (Q6 + Q29 + Q68 + Q118 + Q132 + Q144 + Q199 + Q200) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Obtíže se soustředěním; snadné rozptýlení vnějšími podněty.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Excentricita": {
    en: "Eccentricity", domain: "Psychoticismus",
    items: [20, 23, 24, 32, 69, 70, 151, 171, 184, 204],
    get itemCount() { return this.items.length; },
    formulaExact: "Excentricita = (Q21 + Q24 + Q25 + Q33 + Q70 + Q71 + Q152 + Q172 + Q185 + Q205) / 10",
    formulaMath: "= Σ odpovědí na 10 položek / 10",
    desc: "Divné, neobvyklé nebo bizarní chování, vzhled nebo řeč; zvláštní a nepředvídatelné myšlenky.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Emoční labilita": {
    en: "Emotional Lability", domain: "Negativní afektivita",
    items: [17, 61, 121, 137, 157, 164, 180, 211],
    get itemCount() { return this.items.length; },
    formulaExact: "Emoční labilita = (Q18 + Q62 + Q122 + Q138 + Q158 + Q165 + Q181 + Q212) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Nestabilita emočních prožitků a nálad; emoce se snadno vyvolají, jsou intenzivní.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Grandiozita": {
    en: "Grandiosity", domain: "Antagonismus",
    items: [39, 64, 113, 114, 178, 186, 196, 197],
    get itemCount() { return this.items.length; },
    formulaExact: "Grandiozita = (Q40 + Q65 + Q114 + Q115 + Q179 + Q187 + Q197 + Q198) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Přesvědčení, že je člověk nadřazen druhým a zaslouží si zvláštní zacházení.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Hostilita": {
    en: "Hostility", domain: "Negativní afektivita",
    items: [27, 31, 37, 84, 115, 169, 187, 215],
    get itemCount() { return this.items.length; },
    formulaExact: "Hostilita = (Q28 + Q32 + Q38 + Q85 + Q116 + Q170 + Q188 + Q216) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Přetrvávající nebo časté pocity hněvu; podrážděnost v reakci na drobné urážky.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Impulzivita": {
    en: "Impulsivity", domain: "Disinhibice",
    items: [3, 4, 14, 21, 128, 158, 203, 219],
    get itemCount() { return this.items.length; },
    formulaExact: "Impulzivita = (Q4 + Q5 + Q15 + Q22 + Q129 + Q159 + Q204 + Q220) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Jednání na základě momentálního impulzu; obtížná schopnost následovat plán.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Vyhýbání se intimitě": {
    en: "Intimacy Avoidance", domain: "Odtažitost",
    items: [9, 81, 88, 107, 119, 144, 145, 202],
    get itemCount() { return this.items.length; },
    formulaExact: "Vyhýbání se intimitě = (Q10 + Q82 + Q89 + Q108 + Q120 + Q145 + Q146 + Q203) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Vyhýbání se blízkým nebo romantickým vztahům a intimnímu kontaktu.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Nezodpovědnost": {
    en: "Irresponsibility", domain: "Disinhibice",
    items: [30, 46, 86, 88, 159, 170, 200, 209],
    get itemCount() { return this.items.length; },
    formulaExact: "Nezodpovědnost = (Q31 + Q47 + Q87 + Q89 + Q160 + Q171 + Q201 + Q210) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Nedodržování finančních a jiných závazků; neplnění dohod a slibů.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Manipulativnost": {
    en: "Manipulativeness", domain: "Antagonismus",
    items: [55, 72, 75, 106, 124, 125, 134, 179],
    get itemCount() { return this.items.length; },
    formulaExact: "Manipulativnost = (Q56 + Q73 + Q76 + Q107 + Q125 + Q126 + Q135 + Q180) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Používání lstivosti k ovlivňování nebo kontrole druhých; svádění, šarm, výřečnost.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Percepční dysregulace": {
    en: "Perceptual Dysregulation", domain: "Psychoticismus",
    items: [35, 36, 41, 43, 58, 76, 93, 98, 138, 142, 149, 192, 194, 212, 216],
    get itemCount() { return this.items.length; },
    formulaExact: "Percepční dysregulace = (Q36 + Q37 + Q42 + Q44 + Q59 + Q77 + Q94 + Q99 + Q139 + Q143 + Q150 + Q193 + Q195 + Q213 + Q217) / 15",
    formulaMath: "= Σ odpovědí na 15 položek / 15",
    desc: "Zvláštní smyslové zážitky; smíšení reality a fantazie; depersonalizace a derealizace.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Perseverace": {
    en: "Perseveration", domain: "Negativní afektivita",
    items: [45, 59, 77, 79, 99, 120, 127, 136],
    get itemCount() { return this.items.length; },
    formulaExact: "Perseverace = (Q46 + Q60 + Q78 + Q80 + Q100 + Q121 + Q128 + Q137) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Setrvávání u nefunkčních přístupů; obtížná změna chování navzdory opakovaným neúspěchům.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Restriktivní afektivita": {
    en: "Restricted Affectivity", domain: "Odtažitost",
    items: [7, 83, 90, 100, 146, 166, 183, 167],
    get itemCount() { return this.items.length; },
    formulaExact: "Restriktivní afektivita = (Q8 + Q84 + Q91 + Q101 + Q147 + Q167 + Q184 + Q168) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Malá reakce na emocionálně stimulující situace; omezené prožívání i projevování emocí.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Riskování": {
    en: "Risk Taking", domain: "Disinhibice",
    items: [6, 34, 38, 47, 48, 66, 68, 87, 96, 97, 111, 163, 195, 214],
    get itemCount() { return this.items.length; },
    formulaExact: "Riskování = (Q7 + Q35 + Q39 + Q48 + Q49 + Q67 + Q69 + Q88 + Q97 + Q98 + Q112 + Q164 + Q196 + Q215) / 14",
    formulaMath: "= Σ odpovědí na 14 položek / 14",
    desc: "Účast na nebezpečných aktivitách bez ohledu na důsledky. ⚠ Na úrovni domény invertováno (pól kompulzivity).",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Separační nejistota": {
    en: "Separation Insecurity", domain: "Negativní afektivita",
    items: [11, 49, 56, 63, 126, 148, 174, 201],
    get itemCount() { return this.items.length; },
    formulaExact: "Separační nejistota = (Q12 + Q50 + Q57 + Q64 + Q127 + Q149 + Q175 + Q202) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Strach z odmítnutí nebo oddělení od významných druhých; obavy ze ztráty.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Submisivita": {
    en: "Submissiveness", domain: "Negativní afektivita",
    items: [8, 15, 16, 62, 63, 201, 202, 9],
    get itemCount() { return this.items.length; },
    formulaExact: "Submisivita = (Q9 + Q16 + Q17 + Q63 + Q64 + Q202 + Q203 + Q10) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Přizpůsobení se přáním a potřebám druhých; podřizování vlastního jednání.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Podezřívavost": {
    en: "Suspiciousness", domain: "Odtažitost",
    items: [1, 102, 116, 117, 132, 133, 176, 189],
    get itemCount() { return this.items.length; },
    formulaExact: "Podezřívavost = (Q2 + Q103 + Q117 + Q118 + Q133 + Q134 + Q177 + Q190) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Očekávání zlomyslnosti od druhých; pochybování o loajalitě.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Neobvyklé přesvědčení": {
    en: "Unusual Beliefs & Experiences", domain: "Psychoticismus",
    items: [93, 94, 142, 143, 149, 150, 192, 205],
    get itemCount() { return this.items.length; },
    formulaExact: "Neobvyklé přesvědčení = (Q94 + Q95 + Q143 + Q144 + Q150 + Q151 + Q193 + Q206) / 8",
    formulaMath: "= Σ odpovědí na 8 položek / 8",
    desc: "Přesvědčení o nadpřirozených schopnostech; neobvyklé zážitky s realitou.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Stažení": {
    en: "Withdrawal", domain: "Odtažitost",
    items: [9, 74, 81, 82, 119, 135, 145, 161, 182, 185, 207],
    get itemCount() { return this.items.length; },
    formulaExact: "Stažení = (Q10 + Q75 + Q82 + Q83 + Q120 + Q136 + Q146 + Q162 + Q183 + Q186 + Q208) / 11",
    formulaMath: "= Σ odpovědí na 11 položek / 11",
    desc: "Preference pro samotu; rezervovanost v sociálních situacích.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
  "Rigidita": {
    en: "Rigid Perfectionism", domain: "Disinhibice",
    items: [33, 49, 51, 60, 78, 80, 104, 115, 122, 135, 139, 175, 196, 219],
    get itemCount() { return this.items.length; },
    formulaExact: "Rigidita = (Q34 + Q50 + Q52 + Q61 + Q79 + Q81 + Q105 + Q116 + Q123 + Q136 + Q140 + Q176 + Q197 + Q220) / 14",
    formulaMath: "= Σ odpovědí na 14 položek / 14",
    desc: "Přísné trvání na dokonalosti; rigidní dodržování pravidel. ⚠ Na úrovni domény invertováno.",
    source: "krueger2012", scoringSource: "apaPid5",
  },
};

// ═══ Domain Metadata ═══
export const DOMAIN_META = {
  "Negativní afektivita": {
    en: "Negative Affectivity",
    coreFacets: ["Emoční labilita", "Úzkostnost", "Separační nejistota"],
    allFacets: ["Emoční labilita", "Úzkostnost", "Separační nejistota", "Hostilita", "Perseverace", "Submisivita", "Restriktivní afektivita"],
    formulaExact: "Neg. afektivita = průměr(Emoční labilita, Úzkostnost, Sep. nejistota, Hostilita, Perseverace, Submisivita, Restriktivní afektivita)",
    formulaOfficial: "APA oficiální = (Emoční labilita + Úzkostnost + Separační nejistota) / 3",
    desc: "Časté a intenzivní prožívání negativních emocí a projevů chování z nich vyplývajících.",
    source: "krueger2012", cutoffSource: "bach2018",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Odtažitost": {
    en: "Detachment",
    coreFacets: ["Stažení", "Anhedonie", "Vyhýbání se intimitě"],
    allFacets: ["Stažení", "Vyhýbání se intimitě", "Anhedonie", "Depresivita", "Restriktivní afektivita", "Podezřívavost"],
    formulaExact: "Odtažitost = průměr(Stažení, Vyh. se intimitě, Anhedonie, Depresivita, Restriktivní afektivita, Podezřívavost)",
    formulaOfficial: "APA oficiální = (Stažení + Anhedonie + Vyhýbání se intimitě) / 3",
    desc: "Stažení z mezilidských interakcí; omezený prožitek a projev emocí.",
    source: "krueger2012", cutoffSource: "bach2018",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Antagonismus": {
    en: "Antagonism",
    coreFacets: ["Manipulativnost", "Klamavost", "Grandiozita"],
    allFacets: ["Manipulativnost", "Klamavost", "Grandiozita", "Vyhášení pozornosti", "Bezcitnost"],
    formulaExact: "Antagonismus = průměr(Manipulativnost, Klamavost, Grandiozita, Vyhášení pozornosti, Bezcitnost)",
    formulaOfficial: "APA oficiální = (Manipulativnost + Klamavost + Grandiozita) / 3",
    desc: "Chování stavějící osobu do konfliktu s druhými; přehnané pocity vlastní důležitosti.",
    source: "krueger2012", cutoffSource: "bach2018",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Disinhibice": {
    en: "Disinhibition",
    coreFacets: ["Nezodpovědnost", "Impulzivita", "Roztříštěnost"],
    allFacets: ["Nezodpovědnost", "Impulzivita", "Roztříštěnost", "Riskování", "Rigidita"],
    formulaExact: "Disinhibice = průměr(Nezodpovědnost, Impulzivita, Roztříštěnost, Riskování, Rigidita)",
    formulaOfficial: "APA oficiální = (Nezodpovědnost + Impulzivita + Roztříštěnost) / 3",
    desc: "Orientace na okamžité uspokojení; impulzivní chování bez ohledu na následky.",
    source: "krueger2012", cutoffSource: "bach2018",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
  "Psychoticismus": {
    en: "Psychoticism",
    coreFacets: ["Neobvyklé přesvědčení", "Excentricita", "Percepční dysregulace"],
    allFacets: ["Neobvyklé přesvědčení", "Excentricita", "Percepční dysregulace"],
    formulaExact: "Psychoticismus = průměr(Neobvyklé přesvědčení, Excentricita, Percepční dysregulace)",
    formulaOfficial: "APA oficiální = (Neobvyklé přesvědčení + Excentricita + Percepční dysregulace) / 3",
    desc: "Široké spektrum kulturně inkongruentních, zvláštních chování a myšlení.",
    source: "krueger2012", cutoffSource: "bach2018",
    cutoffLabels: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
  },
};

// ═══ General scoring info ═══
export const SCORING_INFO = {
  pid5: {
    scale: "0–3 (0 = Zcela nepravdivé, 1 = Částečně nepravdivé, 2 = Částečně pravdivé, 3 = Zcela pravdivé)",
    facetFormula: "Facetové skóre = průměr odpovědí na všechny položky dané facety (rozsah 0.00–3.00)",
    facetFormulaMath: "facet_score = Σ(item_responses) / n_items",
    domainFormula: "Doménové skóre = průměr facetových skórů přiřazených k doméně",
    domainFormulaMath: "domain_score = Σ(facet_scores) / n_facets_in_domain",
    diagFormula: "Diagnostické skóre = vážený průměr relevantních facetových skórů (váhy dle DSM-5 AMPD profilů)",
    diagFormulaMath: "diag_score = Σ(facet_score × weight) / Σ(weights)",
    cutoffs: "< 1.0 Nízké · 1.0–1.5 Mírné · ≥ 1.5 Zvýšené · ≥ 2.0 Vysoké",
    cutoffSource: "bach2018",
    source: "krueger2012",
    itemCount: 220, facetCount: 25, domainCount: 5,
  },
  lpfs: {
    scale: "1–4 (1 = Zcela nepravdivé, 2 = Trochu pravdivé, 3 = Převážně pravdivé, 4 = Zcela pravdivé)",
    totalFormula: "Celkové skóre = průměr všech 80 odpovědí",
    totalFormulaMath: "total_score = Σ(item_responses) / 80",
    subscales: "Identita (20 položek) · Sebesměrování (20) · Empatie (20) · Intimita (20)",
    subscaleFormula: "Subškálové skóre = průměr 20 položek dané subškály",
    higherOrder: "Sebe-fungování = průměr(Identita, Sebesměrování) · Interpersonální = průměr(Empatie, Intimita)",
    threshold: "Práh pro PD diagnózu: průměr ≥ 1.5 (= LPFS Level 2+, minimum pro diagnózu PD dle DSM-5 AMPD)",
    source: "morey2017",
    itemCount: 80,
  },
};
